services:
  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    ports:
    - 27017:27017