PUT http://localhost:8080/api/users/verify-email/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2OGM3ZWExOWM2MjI2YmJlN2E0YWEwNjQiLCJpYXQiOjE3NTc5MzIwNTd9.yCth_pvi3umSr9yx4mAJ2d8gjwDcFxwyHeWw3osTP6E
content-type: application/json