name: Pipeline

on: [push]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env: 
      BACK_PORT: 3001
      MONGODB_URI: mongodb://tester:pass@localhost/?authMechanism=DEFAULT&authSource=admin
      EXPIRE_DELAY: 30
      SECRET: secret
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Start mongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '8.0'
        mongodb-username: tester
        mongodb-password: pass
        mongodb-db: test
    - name: Create image directories
      run: |
        mkdir ../uploads
        mkdir ../output
    
    - name: Install dependencies
      run: npm install
    
    - name: Run backend tests
      run: npm test
      
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      BACKEND_URL: http:localhost:3001/api
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run frontend tests
      run: npm test